set_property IOSTANDARD LVCMOS33 [get_ports {A_2_GLeft4[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A_2_GLeft4[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A_2_GLeft4[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A_2_GLeft4[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A_2_GLeft4[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A_2_GLeft4[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A_2_GLeft4[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A_2_GRight4[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A_2_GRight4[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A_2_GRight4[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A_2_GRight4[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A_2_GRight4[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A_2_GRight4[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A_2_GRight4[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DigitalSel[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DigitalSel[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DigitalSel[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DigitalSel[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DigitalSel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DigitalSel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DigitalSel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DigitalSel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports Clk]
set_property IOSTANDARD LVCMOS33 [get_ports DpLeft]
set_property IOSTANDARD LVCMOS33 [get_ports En]
set_property IOSTANDARD LVCMOS33 [get_ports DpRight]

set_property PACKAGE_PIN P17 [get_ports Clk]
set_property PACKAGE_PIN D5 [get_ports DpLeft]
set_property PACKAGE_PIN G2 [get_ports {DigitalSel[7]}]
set_property PACKAGE_PIN C2 [get_ports {DigitalSel[6]}]
set_property PACKAGE_PIN C1 [get_ports {DigitalSel[5]}]
set_property PACKAGE_PIN H1 [get_ports {DigitalSel[4]}]
set_property PACKAGE_PIN G1 [get_ports {DigitalSel[3]}]
set_property PACKAGE_PIN F1 [get_ports {DigitalSel[2]}]
set_property PACKAGE_PIN E1 [get_ports {DigitalSel[1]}]
set_property PACKAGE_PIN G6 [get_ports {DigitalSel[0]}]
set_property PACKAGE_PIN B2 [get_ports {A_2_GLeft4[6]}]
set_property PACKAGE_PIN B3 [get_ports {A_2_GLeft4[5]}]
set_property PACKAGE_PIN A1 [get_ports {A_2_GLeft4[4]}]
set_property PACKAGE_PIN B1 [get_ports {A_2_GLeft4[3]}]
set_property PACKAGE_PIN A3 [get_ports {A_2_GLeft4[2]}]
set_property PACKAGE_PIN A4 [get_ports {A_2_GLeft4[1]}]
set_property PACKAGE_PIN B4 [get_ports {A_2_GLeft4[0]}]
set_property PACKAGE_PIN D2 [get_ports {A_2_GRight4[6]}]
set_property PACKAGE_PIN E2 [get_ports {A_2_GRight4[5]}]
set_property PACKAGE_PIN F3 [get_ports {A_2_GRight4[4]}]
set_property PACKAGE_PIN D4 [get_ports {A_2_GRight4[0]}]
set_property PACKAGE_PIN D3 [get_ports {A_2_GRight4[2]}]
set_property PACKAGE_PIN E3 [get_ports {A_2_GRight4[1]}]
set_property PACKAGE_PIN F4 [get_ports {A_2_GRight4[3]}]
set_property PACKAGE_PIN H2 [get_ports DpRight]

set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
set_property PACKAGE_PIN P5 [get_ports {sw[7]}]
set_property PACKAGE_PIN P4 [get_ports {sw[6]}]
set_property PACKAGE_PIN P3 [get_ports {sw[5]}]
set_property PACKAGE_PIN P2 [get_ports {sw[4]}]
set_property PACKAGE_PIN R2 [get_ports {sw[3]}]
set_property PACKAGE_PIN M4 [get_ports {sw[2]}]
set_property PACKAGE_PIN N4 [get_ports {sw[1]}]
set_property PACKAGE_PIN R1 [get_ports {sw[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports start]
set_property PACKAGE_PIN U4 [get_ports start]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets start]
#set_property IOSTANDARD LVCMOS33 [get_ports Button]
#set_property PACKAGE_PIN V1 [get_ports Button]





